services:
  accounts:
    image: "shi2gami42/d-bank_accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - d-bank-network
  loans:
    image: "shi2gami42/d-bank-loans:microservices"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - d-bank-network
  cards:
    image: "shi2gami42/d-bank-cards:microservices"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
        - d-bank-network
networks:
    d-bank-network:
        driver: "bridge"