server:
  port: 8080
spring:
  profiles:
    active:
      - "qa"
      - "prod"
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  datasource:
    url: jdbc:h2:mem:bankdb
    driver-class-name: org.h2.Driver
    username: admin
    password: ''
  h2:
    console:
      enabled: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

build:
  version: "3.0.0"

accounts:
  message: "Welcome to Duncan Cadoret Bank accounts related services"
  contactDetails:
    name: "Duncan Cadoret"
    role: "Software Engineer One day"
    website: "https://duncan-cadoret.com/"
  onCallSupport:
    - (33) 6 12 34 56 78
    - (33) 6 12 34 56 79